In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,KFold,cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.datasets import california_housing

### Data extraction for this particular example

In [2]:
data = california_housing.fetch_california_housing()

### Features vs Target separation

In [3]:
X = pd.DataFrame(data['data'],columns=data['feature_names'])
y = pd.DataFrame(data['target'])

### A bit of Exploratory Data Analisis

In [4]:
X.shape

(20640, 8)

In [5]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
y.head()

0
0  4.526
1  3.585
2  3.521
3  3.413
4  3.422

# Train vs Test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state=42)

In [8]:
X_train.shape

(16512, 8)

In [9]:
X_test.shape

(4128, 8)

### Training and validating with Train test split

In [10]:
lin_reg = LinearRegression()

In [11]:
lin_reg.fit(X_train,y_train);

In [12]:
lin_reg.score(X_train,y_train)

0.6125511913966952

In [13]:
lin_reg.score(X_test,y_test)

0.575787706032451

# Kfold Cross-Validation

In [14]:
# Determining how we would like the data to be split
kf = KFold(5, random_state=888,shuffle=True)

In [15]:
kf

KFold(n_splits=5, random_state=888, shuffle=True)

In [16]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [    0     1     2 ... 20636 20637 20639] TEST: [   21    30    36 ... 20631 20632 20638]
TRAIN: [    2     3     4 ... 20637 20638 20639] TEST: [    0     1     5 ... 20616 20624 20625]
TRAIN: [    0     1     2 ... 20636 20638 20639] TEST: [    7    22    25 ... 20634 20635 20637]
TRAIN: [    0     1     4 ... 20635 20637 20638] TEST: [    2     3     8 ... 20623 20636 20639]
TRAIN: [    0     1     2 ... 20637 20638 20639] TEST: [    4     6    15 ... 20626 20627 20629]


### Training and Validating with KFolds

In [17]:
lin_reg = LinearRegression()

In [18]:
result = cross_validate(lin_reg,X,y,cv=kf,
               return_train_score=True, return_estimator=True)

In [23]:
result

{'fit_time': array([0.00621176, 0.00499916, 0.00452709, 0.00459099, 0.00346494]),
 'score_time': array([0.00244117, 0.00271082, 0.0023191 , 0.00167513, 0.00168514]),
 'estimator': (LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
  LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
  LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
  LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False),
  LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)),
 'test_score': array([0.61292219, 0.59403748, 0.60012767, 0.59645999, 0.60437023]),
 'train_score': array([0.6042293 , 0.60805321, 0.6076259 , 0.60852969, 0.60452869])}

In [19]:
result['train_score']

array([0.6042293 , 0.60805321, 0.6076259 , 0.60852969, 0.60452869])

In [21]:
result['test_score']

array([0.61292219, 0.59403748, 0.60012767, 0.59645999, 0.60437023])

### Comparing the mean of the splits - Train vs Test

In [20]:
np.mean(result['train_score'])

0.6065933558414665

In [22]:
np.mean(result['test_score'])

0.6015835107933778

# Train / Validation / Test split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=1000, random_state=42)

In [61]:
X_train_v, X_val, y_train_v, y_val = train_test_split(X_train,y_train,test_size=1000, random_state=123)

### Training and Validating with Train / Validation / Test

In [62]:
lin_reg = LinearRegression()

In [63]:
lin_reg.fit(X_train_v,y_train_v);

In [65]:
lin_reg.score(X_train_v,y_train_v)

0.6076265709233504

In [66]:
lin_reg.score(X_val,y_val)

0.5812494792349636

### If we are happy with our final model we proceed to check its performance on the TEST dataset 

In [50]:
lin_reg.fit(X_train,y_train);
lin_reg.score(X_test,y_test)

0.602740734398064

# Nested KFold

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state=42)

In [52]:
kf = KFold(5, random_state=777,shuffle=True)

### Training and Validating with Nested KFold

In [53]:
result = cross_validate(lin_reg,X_train,y_train,cv=kf,
               return_train_score=True, return_estimator=True)

In [55]:
result['train_score']

array([0.61333341, 0.61177594, 0.61425314, 0.60872481, 0.61512626])

In [56]:
# Checking CV validation performance
result['test_score']

array([0.60898237, 0.61509977, 0.60495645, 0.62649744, 0.60103304])

In [57]:
np.mean(result['train_score'])

0.6126427126239944

In [58]:
# Checking CV validation performance
np.mean(result['test_score'])

0.6113138138821974

### If we are happy with our final model we proceed to check its performance on the TEST dataset 

In [59]:
lin_reg.fit(X_train,y_train)
lin_reg.score(X_test,y_test)

0.575787706032451